"use client";
import { useEffect, useMemo, useState } from "react";
import type { Card, CharacterConfig, Effects, GameConfig, GameState, ResolutionOption, StatKey } from "@/lib/types";

const statKeys:StatKey[]=["stamina","intelligence","eq","mood","money"];
const statLabels:Record<StatKey,string>={stamina:"體力",intelligence:"智力",eq:"情商",mood:"心情",money:"金錢"};
const stageNames=["找工作","進入職場學習","完成重大專案／獲得地位","經歷低谷","靠信仰站立／成為大師"];

function Portrait({id,name}:{id:string;name:string}){return <span className={'character-portrait portrait-'+id+' portrait-normal'} role="img" aria-label={name}/>;}
function StatEditor({title,value,onChange,compact=false}:{title:string;value?:Effects;onChange:(next:Effects)=>void;compact?:boolean}){
 const change=(key:StatKey,next:number)=>onChange({...value,[key]:Number.isFinite(next)?next:0});
 return <div className={`stat-editor ${compact?"compact":""}`}><div className="stat-editor-title">{title}</div><div className="stat-editor-grid">{statKeys.map(key=>{const step=key==="money"?100:1;return <div className="stat-control" key={key}><span>{statLabels[key]}</span><div><button type="button" aria-label={`${statLabels[key]}減少`} onClick={()=>change(key,(value?.[key]??0)-step)}>−</button><input type="number" step={step} value={value?.[key]??0} onChange={e=>change(key,Number(e.target.value))}/><button type="button" aria-label={`${statLabels[key]}增加`} onClick={()=>change(key,(value?.[key]??0)+step)}>＋</button></div></div>})}</div></div>
}
function CounterEditor({title,value=0,onChange}:{title:string;value?:number;onChange:(next:number)=>void}){
 return <div className="special-counter"><span>{title}</span><div><button type="button" onClick={()=>onChange(Math.max(0,value-1))}>−</button><b>{value}</b><button type="button" onClick={()=>onChange(value+1)}>＋</button></div></div>
}

export default function AdminApp(){
 const[auth,setAuth]=useState<boolean|null>(null);const[password,setPassword]=useState("");const[config,setConfig]=useState<GameConfig|null>(null);const[game,setGame]=useState<GameState|null>(null);const[adjusting,setAdjusting]=useState("");
 const[tab,setTab]=useState<"cards"|"cells"|"characters"|"live">("cards");const[character,setCharacter]=useState("zoey");const[stage,setStage]=useState(1);const[type,setType]=useState<"chance"|"destiny">("chance");const[msg,setMsg]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/admin/session").then(r=>r.json()),fetch("/api/config").then(r=>r.json()),fetch("/api/game",{cache:"no-store"}).then(r=>r.json())]).then(([a,c,g])=>{setAuth(a.authenticated);setConfig(c.config);setGame(g.state)})},[]);
 useEffect(()=>{if(!auth)return;const load=()=>fetch("/api/game",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(data=>data?.state&&setGame(data.state));const timer=setInterval(load,2000);return()=>clearInterval(timer)},[auth]);
 const adjustStat=async(characterId:string,key:StatKey,delta:number)=>{
  if(!game||adjusting)return;const current=game.players[characterId].stats[key];const raw=current+delta;const next=key==="mood"?Math.min(10,Math.max(0,raw)):Math.max(0,raw);
  setAdjusting(characterId+key);setGame(previous=>{if(!previous)return previous;const copy=structuredClone(previous);copy.players[characterId].stats[key]=next;return copy});
  try{const r=await fetch("/api/admin/game",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({characterId,stats:{[key]:next}})});const data=await r.json();if(!r.ok)throw 0;setGame(data.state);setMsg("已即時調整角色能力。")}catch{setMsg("能力調整失敗，請重新登入。")}finally{setAdjusting("")}
 }; const login=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok){setAuth(true);setPassword("");setMsg("")}else setMsg("密碼不正確")};
 const publish=async()=>{setMsg("發布中…");const r=await fetch("/api/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({config})});setMsg(r.ok?"已發布！新設定立即套用到目前遊戲。":"發布失敗，請重新登入。")};
 const reset=async()=>{if(!confirm("確定要清除目前遊戲進度？卡片與格子設定不會被刪除。"))return;const r=await fetch("/api/admin/reset",{method:"POST"});setMsg(r.ok?"遊戲已重置。":"重置失敗。")};
 const logout=async()=>{await fetch("/api/admin/logout",{method:"POST"});setAuth(false)};
 const cards=useMemo(()=>config?.cards.filter(c=>c.characterId===character&&c.contentStage===stage&&c.type===type)||[],[config,character,stage,type]);
 const updateCard=(id:string,patch:Partial<Card>)=>setConfig(c=>c?{...c,cards:c.cards.map(x=>x.id===id?{...x,...patch}:x)}:c);
 const updateOption=(card:Card,key:"optionA"|"optionB",patch:Partial<ResolutionOption>)=>updateCard(card.id,{[key]:{label:card[key]?.label||"",effects:card[key]?.effects||{},...patch}});
 const addCard=()=>setConfig(c=>{if(!c)return c;const id=`${character}-${type}-${stage}-custom-${Date.now()}`;return{...c,cards:[...c.cards,{id,characterId:character,contentStage:stage,type,title:"新卡片",description:"請輸入事件內容",effects:{},resolutionMode:"automatic"}]}});
 const updateStartReward=(characterId:string,next:number)=>setConfig(current=>current?{...current,cells:current.cells.map(cell=>cell.id===0?{...cell,startRewards:{...cell.startRewards,[characterId]:Math.max(0,next)}}:cell)}:current); const updateCharacter=(id:string,updater:(item:CharacterConfig)=>CharacterConfig)=>setConfig(c=>c?{...c,characters:c.characters.map(x=>x.id===id?updater(x):x)}:c);
 if(auth===null||!config)return <main className="loading"><div className="spinner">⚙️</div><p>正在開啟管理後台…</p></main>;
 if(!auth)return <main className="admin-login"><a href="/" className="back-link">← 回到遊戲</a><form onSubmit={login} className="login-card card"><span className="admin-icon">🔐</span><p className="eyebrow">HOST CONTROL</p><h1>主持人管理介面</h1><p>請輸入管理密碼，才能編輯遊戲內容或重置進度。</p><label>管理密碼<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/></label>{msg&&<p className="error">{msg}</p>}<button className="primary wide">登入管理後台</button></form></main>;
 return <main className="admin-page"><header className="admin-header"><div><a href="/" className="back-link">← 回到遊戲</a><p className="eyebrow">HOST CONTROL</p><h1>遊戲內容管理</h1></div><div><button className="ghost danger" onClick={reset}>重置本局</button><button className="primary" onClick={publish}>發布修改</button><button className="text-button" onClick={logout}>登出</button></div></header>
 {msg&&<div className="notice">{msg}</div>}<div className="admin-shell"><aside className="admin-tabs"><button className={tab==="cards"?"active":""} onClick={()=>setTab("cards")}>🃏 機會命運卡</button><button className={tab==="cells"?"active":""} onClick={()=>setTab("cells")}>🗺️ 地圖格子</button><button className={tab==="characters"?"active":""} onClick={()=>setTab("characters")}>👥 角色與門檻</button><button className={tab==="live"?"active":""} onClick={()=>setTab("live")}>📊 角色即時能力</button><div className="publish-note"><b>發布規則</b><p>按下發布後，修改會立即影響目前遊戲之後的抽卡、格子與判定，不回溯已完成事件。</p></div></aside>
 <section className="admin-content card">{tab==="live"&&<><section className="live-players card"><div className="live-players-title"><span>LIVE</span><b>即時角色能力</b></div>{game&&config.characters.map(c=>{const p=game.players[c.id];return <article className="live-player" key={c.id}><div className="live-player-head"><Portrait id={c.id} name={c.name}/><div><h3>{c.name}</h3><small>職稱：{c.titles[p.stage]||"尚未設定"}・目標 {c.job}</small></div></div><div className="live-stat-grid">{(["stamina","intelligence","eq","mood","money"] as StatKey[]).map(key=>{const step=key==="money"?100:1;return <div className="live-stat" key={key}><span>{statLabels[key]}</span><div><button type="button" disabled={!!adjusting} onClick={()=>adjustStat(c.id,key,-step)}>−</button><b>{p.stats[key]}</b><button type="button" disabled={!!adjusting} onClick={()=>adjustStat(c.id,key,step)}>＋</button></div></div>})}</div></article>})}</section></>}
 {tab==="cards"&&<><div className="admin-title"><div><p className="eyebrow">CARD LIBRARY</p><h2>卡片資料庫</h2></div><button className="ghost" onClick={addCard}>＋ 新增卡片</button></div>
 <div className="filters"><select value={character} onChange={e=>setCharacter(e.target.value)}>{config.characters.map(c=><option value={c.id} key={c.id}>{c.name}・{c.job}</option>)}</select><select value={stage} onChange={e=>setStage(Number(e.target.value))}>{stageNames.map((name,i)=><option value={i+1} key={name}>階段 {i+1}・{name}</option>)}</select><select value={type} onChange={e=>setType(e.target.value as "chance"|"destiny")}><option value="chance">機會卡</option><option value="destiny">命運卡</option></select></div>
 <p className="count">{cards.length} 張卡片（每個牌組原則為 4 張；抽完前不重複）</p><div className="editor-list">{cards.map((card,i)=>{const mode=card.resolutionMode??(card.task?"task":"automatic");return <article className="editor-card card-editor" key={card.id}><div className="number">{i+1}</div><div className="editor-fields"><label>卡片名稱<input value={card.title} onChange={e=>updateCard(card.id,{title:e.target.value})}/></label><label>事件說明<textarea value={card.description} onChange={e=>updateCard(card.id,{description:e.target.value})}/></label><label>現場動態指令（沒有可留白）<textarea value={card.instruction||""} placeholder="例如：帶領全場做 3 個 Pose" onChange={e=>updateCard(card.id,{instruction:e.target.value})}/></label>
 <label>結算方式<select value={mode} onChange={e=>updateCard(card.id,{resolutionMode:e.target.value as Card["resolutionMode"],task:e.target.value==="task"})}><option value="automatic">直接套用一般效果</option><option value="task">由主持人判定成功／失敗</option><option value="choice">讓玩家二選一</option></select></label>
 {mode==="automatic"&&<><StatEditor title="一般效果" value={card.effects} onChange={effects=>updateCard(card.id,{effects})}/><CounterEditor title="獲得平安卡" value={card.peaceCards} onChange={peaceCards=>updateCard(card.id,{peaceCards})}/></>}
 {mode==="task"&&<div className="resolution-panels"><div><label>成功按鈕文字<input value={card.successLabel||"任務成功"} onChange={e=>updateCard(card.id,{successLabel:e.target.value})}/></label><StatEditor title="成功效果" value={card.successEffects} onChange={successEffects=>updateCard(card.id,{successEffects})}/><CounterEditor title="成功時獲得平安卡" value={card.successPeaceCards} onChange={successPeaceCards=>updateCard(card.id,{successPeaceCards})}/></div><div><label>失敗按鈕文字<input value={card.failureLabel||"任務失敗"} onChange={e=>updateCard(card.id,{failureLabel:e.target.value})}/></label><StatEditor title="失敗效果" value={card.failureEffects} onChange={failureEffects=>updateCard(card.id,{failureEffects})}/><CounterEditor title="失敗時獲得平安卡" value={card.failurePeaceCards} onChange={failurePeaceCards=>updateCard(card.id,{failurePeaceCards})}/></div></div>}
 {mode==="choice"&&<div className="resolution-panels"><div><label>選項一名稱<input value={card.optionA?.label||""} onChange={e=>updateOption(card,"optionA",{label:e.target.value})}/></label><StatEditor title="選項一效果" value={card.optionA?.effects} onChange={effects=>updateOption(card,"optionA",{effects})}/><CounterEditor title="選項一獲得平安卡" value={card.optionA?.peaceCards} onChange={peaceCards=>updateOption(card,"optionA",{peaceCards})}/><label>選項一結果描述<textarea value={card.optionA?.resultDescription||"真好！"} onChange={e=>updateOption(card,"optionA",{resultDescription:e.target.value})}/></label></div><div><label>選項二名稱<input value={card.optionB?.label||""} onChange={e=>updateOption(card,"optionB",{label:e.target.value})}/></label><StatEditor title="選項二效果" value={card.optionB?.effects} onChange={effects=>updateOption(card,"optionB",{effects})}/><CounterEditor title="選項二獲得平安卡" value={card.optionB?.peaceCards} onChange={peaceCards=>updateOption(card,"optionB",{peaceCards})}/><label>選項二結果描述<textarea value={card.optionB?.resultDescription||"真好！"} onChange={e=>updateOption(card,"optionB",{resultDescription:e.target.value})}/></label></div></div>}
 </div><button className="icon-button danger" title="刪除" onClick={()=>setConfig(c=>c?{...c,cards:c.cards.filter(x=>x.id!==card.id)}:c)}>×</button></article>})}</div></>}
 {tab==="cells"&&<><div className="admin-title"><div><p className="eyebrow">BOARD EDITOR</p><h2>20 格人生地圖</h2></div></div><div className="editor-list">{config.cells.map(cell=><article className="editor-card" key={cell.id}><div className="number">{cell.id}</div><div className="editor-fields"><div className="inline-fields"><label>圖示<input value={cell.icon} onChange={e=>setConfig(c=>c?{...c,cells:c.cells.map(x=>x.id===cell.id?{...x,icon:e.target.value}:x)}:c)}/></label><label>格子名稱<input value={cell.label} onChange={e=>setConfig(c=>c?{...c,cells:c.cells.map(x=>x.id===cell.id?{...x,label:e.target.value}:x)}:c)}/></label></div><label>說明<textarea value={cell.description} onChange={e=>setConfig(c=>c?{...c,cells:c.cells.map(x=>x.id===cell.id?{...x,description:e.target.value}:x)}:c)}/></label>{cell.id!==0&&<StatEditor title="格子效果" value={cell.effects} onChange={effects=>setConfig(c=>c?{...c,cells:c.cells.map(x=>x.id===cell.id?{...x,effects}:x)}:c)}/>}{cell.id===0&&<section className="start-reward-editor"><div><b>通過起點獎勵</b><small>角色只要路過起點就會立即獲得，不必停留。</small></div><div className="start-reward-grid">{config.characters.map(character=>{const value=cell.startRewards?.[character.id]??0;return <label key={character.id}><span>{character.name}</span><div><button type="button" onClick={()=>updateStartReward(character.id,value-100)}>−</button><input type="number" min="0" step="100" value={value} onChange={event=>updateStartReward(character.id,Number(event.target.value))}/><button type="button" onClick={()=>updateStartReward(character.id,value+100)}>＋</button></div></label>})}</div></section>}<div className="cell-options"><label className="check"><input type="checkbox" checked={!!cell.negative} onChange={e=>setConfig(c=>c?{...c,cells:c.cells.map(x=>x.id===cell.id?{...x,negative:e.target.checked}:x)}:c)}/> 此格為負面事件，可被平安卡抵銷</label><label>暫停回合數<input type="number" min="0" value={cell.skip||0} onChange={e=>setConfig(c=>c?{...c,cells:c.cells.map(x=>x.id===cell.id?{...x,skip:Number(e.target.value)}:x)}:c)}/></label></div></div></article>)}</div></>}
 {tab==="characters"&&<><div className="admin-title"><div><p className="eyebrow">CHARACTERS</p><h2>角色初始值與事件門檻</h2></div></div><div className="editor-list">{config.characters.map(c=><article className="editor-card character-editor" key={c.id}><div className="big-icon" style={{background:c.color}}>{c.icon}</div><div className="editor-fields"><h3>{c.name}・{c.job}</h3><StatEditor title="初始屬性" value={c.initial} onChange={initial=>updateCharacter(c.id,x=>({...x,initial:{...x.initial,...initial}}))}/><div className="threshold-list">{c.thresholds.map((threshold,index)=><section className="threshold-card" key={index}><h4>階段 {index+1}・{stageNames[index]}</h4><p>達到最低門檻並通過起點即可進階；達到完美門檻會獲得額外獎勵。</p><StatEditor compact title="最低門檻" value={threshold.min} onChange={min=>updateCharacter(c.id,x=>({...x,thresholds:x.thresholds.map((t,i)=>i===index?{...t,min}:t)}))}/><label>重大事件描述<textarea className="tall" value={threshold.milestoneDescription||"守護天使的陪伴，讓生涯旅程邁入下階段。"} onChange={e=>updateCharacter(c.id,x=>({...x,thresholds:x.thresholds.map((t,i)=>i===index?{...t,milestoneDescription:e.target.value}:t)}))}/></label><StatEditor compact title="完美通關門檻" value={threshold.perfect} onChange={perfect=>updateCharacter(c.id,x=>({...x,thresholds:x.thresholds.map((t,i)=>i===index?{...t,perfect}:t)}))}/><StatEditor compact title="完美通關獎勵" value={threshold.perfectReward} onChange={perfectReward=>updateCharacter(c.id,x=>({...x,thresholds:x.thresholds.map((t,i)=>i===index?{...t,perfectReward}:t)}))}/><label>完美通關結果描述<textarea value={threshold.perfectDescription||"完美通關！"} onChange={e=>updateCharacter(c.id,x=>({...x,thresholds:x.thresholds.map((t,i)=>i===index?{...t,perfectDescription:e.target.value}:t)}))}/></label></section>)}</div></div></article>)}</div></>}
 </section></div></main>
}
