"use client";
import { useEffect, useRef, useState } from "react";
import type { BoardCell, Card, Effects, GameConfig, GameState, PlayerState, StatKey } from "@/lib/types";
import { SITE_VERSION } from "@/lib/version";

const labels:Record<StatKey,string>={stamina:"體力",intelligence:"智力",eq:"情商",mood:"心情",money:"金錢"};
const stageLabels=["找工作","初入職場學習","重大突破","經歷低谷","靠信仰站立","生涯大師"];
const perimeter=[0,1,2,3,4,5,19,6,18,7,17,8,16,9,15,14,13,12,11,10];
const diceFaces=["⚀","⚁","⚂","⚃","⚄","⚅"];
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
let sharedAudioContext:AudioContext|null=null;
function audioContext(){if(typeof window==="undefined")return null;const Ctor=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!Ctor)return null;sharedAudioContext??=new Ctor();void sharedAudioContext.resume();return sharedAudioContext}
function soundTone(ctx:AudioContext,frequency:number,start:number,duration:number,type:OscillatorType="sine",volume=.08){const oscillator=ctx.createOscillator();const gain=ctx.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.015);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);oscillator.connect(gain).connect(ctx.destination);oscillator.start(start);oscillator.stop(start+duration+.02)}
function playClip(src:string,maxMs:number,volume=.75){if(typeof Audio==="undefined")return;const audio=new Audio(src);audio.volume=volume;void audio.play().catch(()=>{});window.setTimeout(()=>{audio.pause();audio.currentTime=0},maxMs)}
function playOutcome(kind:"cheer"|"sad"){const ctx=audioContext();if(!ctx)return;const now=ctx.currentTime;if(kind==="cheer"){[523,659,784,1047].forEach((frequency,i)=>soundTone(ctx,frequency,now+i*.2,.34,"sine",.075))}else{[392,330,262].forEach((frequency,i)=>soundTone(ctx,frequency,now+i*.28,.38,"triangle",.07))}}
type Pending={kind:"card";card:Card}|{kind:"cardChoice";cards:Card[];type:"chance"|"destiny"}|{kind:"overtime"}|{kind:"class"}|{kind:"info";title:string;description:string};
type StatNotice={characterId:string;stats:Record<StatKey,number>;changes:Partial<Record<StatKey,number>>;contextLabel?:string};
type MilestoneNotice={characterId:string;stage:number;perfect:boolean};
type StartPassNotice={characterId:string;reward:number;money:number};
type PerfectRewardNotice={characterId:string;effects:Effects;description:string};
type ResultNotice={title:string;description:string};

function Portrait({id,size="normal",name}:{id:string;size?:"mini"|"normal"|"large";name:string}){
 return <span className={`character-portrait portrait-${id} portrait-${size}`} role="img" aria-label={name}/>;
}
function applyEffects(p:PlayerState,effects:Effects={}){
 for(const [key,value] of Object.entries(effects) as [StatKey,number][])p.stats[key]+=value;
 p.stats.stamina=Math.max(0,p.stats.stamina);p.stats.intelligence=Math.max(0,p.stats.intelligence);p.stats.eq=Math.max(0,p.stats.eq);
 p.stats.mood=Math.min(10,Math.max(0,p.stats.mood));p.stats.money=Math.max(0,p.stats.money);
}
function effectText(effects?:Effects){if(!effects||!Object.values(effects).some(Boolean))return"無數值變化";return Object.entries(effects).filter(([,v])=>v!==0).map(([k,v])=>`${labels[k as StatKey]} ${Number(v)>0?"+":""}${v}`).join("・")}
function meets(p:PlayerState,req:Partial<Record<StatKey,number>>){return Object.entries(req).every(([k,v])=>p.stats[k as StatKey]>=(v||0))}

export default function GameApp(){
 const[config,setConfig]=useState<GameConfig|null>(null);const[state,setState]=useState<GameState|null>(null);const[loading,setLoading]=useState(true);
 const[pending,setPending]=useState<Pending|null>(null);const[statNotice,setStatNotice]=useState<StatNotice|null>(null);const[milestoneNotice,setMilestoneNotice]=useState<MilestoneNotice|null>(null);const[startPassNotice,setStartPassNotice]=useState<StartPassNotice|null>(null);const[perfectRewardNotice,setPerfectRewardNotice]=useState<PerfectRewardNotice|null>(null);const[resultNotice,setResultNotice]=useState<ResultNotice|null>(null);const[dice,setDice]=useState<number|null>(null);const[rolling,setRolling]=useState(false);
 const[rollMessage,setRollMessage]=useState("");const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);const startNoticeResolver=useRef<(()=>void)|null>(null);const milestoneResolver=useRef<(()=>void)|null>(null);const perfectRewardResolver=useRef<(()=>void)|null>(null);
 useEffect(()=>{if(!state)return;const timer=setInterval(()=>{if(saving||rolling)return;fetch("/api/game",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(data=>{if(!data?.state)return;setState(current=>!current||data.state.lastUpdated>current.lastUpdated?data.state:current)})},2200);return()=>clearInterval(timer)},[saving,rolling,!!state]);
 useEffect(()=>{const timer=setInterval(()=>fetch("/api/config",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(data=>data?.config&&setConfig(data.config)),3000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{fetch("/api/config").then(r=>{if(!r.ok)throw 0;return r.json()}).then(c=>{setConfig(c.config);return fetch("/api/game")}).then(r=>{if(!r.ok)throw 0;return r.json()}).then(g=>{setState(g.state);localStorage.setItem("career-game-cache",JSON.stringify(g.state))}).catch(()=>{const cached=localStorage.getItem("career-game-cache");if(cached)setState(JSON.parse(cached));setMessage("目前離線，先顯示本機暫存進度。")}).finally(()=>setLoading(false))},[]);
 const activeId=state?.turnOrder[state.turnIndex];const active=activeId&&state?.players[activeId];const activeCharacter=config?.characters.find(c=>c.id===activeId);
 const save=async(next:GameState,action:string)=>{setState(next);localStorage.setItem("career-game-cache",JSON.stringify(next));setSaving(true);try{const r=await fetch("/api/game",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({state:next,action})});if(!r.ok)throw 0;const data=await r.json();setState(data.state);localStorage.setItem("career-game-cache",JSON.stringify(data.state));setMessage("")}catch{setMessage("網路暫時中斷，進度已保存在這台裝置。恢復連線後請再進行一步操作。")}finally{setSaving(false)}};
 const nextTurn=(s:GameState)=>{let attempts=0;do{s.turnIndex=(s.turnIndex+1)%s.turnOrder.length;if(s.turnIndex===0)s.round++;attempts++}while(s.players[s.turnOrder[s.turnIndex]].finishedAt!==null&&attempts<s.turnOrder.length)};
 const log=(s:GameState,text:string)=>{s.log=[text,...s.log].slice(0,40)};
 const statChanges=(before:Record<StatKey,number>,after:Record<StatKey,number>)=>Object.fromEntries((Object.keys(after) as StatKey[]).map(key=>[key,after[key]-before[key]]).filter(([,value])=>value!==0)) as Partial<Record<StatKey,number>>;
 const notifyStats=(characterId:string,before:Record<StatKey,number>,after:Record<StatKey,number>,contextLabel?:string)=>{const changes=statChanges(before,after);if(Object.keys(changes).length)setStatNotice({characterId,stats:{...after},changes,contextLabel})};
 const settle=(s:GameState,cell:BoardCell,p:PlayerState)=>{
  if(cell.type==="church"){p.peaceCards++;setResultNotice({title:"獲得平安卡",description:"來到教會，獲得平安卡 ×1"});log(s,`${activeCharacter?.name}獲得一張平安卡 🕊️`)}
  else if(cell.negative&&p.peaceCards>0){p.peaceCards--;log(s,`平安卡自動發動，抵銷「${cell.label}」的負面影響！`);setPending({kind:"info",title:"平安守護！",description:`平安卡自動抵銷了「${cell.label}」的負面影響。`});return false}
  else{applyEffects(p,cell.effects);if(cell.skip)p.skipTurns+=cell.skip;log(s,`${activeCharacter?.name}來到「${cell.label}」：${cell.description}`)}
  return true;
 };
 const drawCard=(s:GameState,p:PlayerState,type:"chance"|"destiny")=>{
  if(!config)return;const contentStage=Math.min(p.stage+1,5);const pool=config.cards.filter(c=>c.characterId===p.characterId&&c.contentStage===contentStage&&c.type===type);
  const key=`${type}-${contentStage}`;let used=p.decks[key]||[];let available=pool.filter(c=>!used.includes(c.id));if(!available.length){used=[];available=pool}
  const cards=[...available].sort(()=>Math.random()-.5).slice(0,Math.min(3,available.length));if(!cards.length)return;setPending({kind:"cardChoice",cards,type});log(s,`來到${type==="chance"?"機會":"命運"}卡選擇時刻`);
 };
 const confirmStartPass=()=>{setStartPassNotice(null);startNoticeResolver.current?.();startNoticeResolver.current=null};
 const confirmMilestone=()=>{setMilestoneNotice(null);milestoneResolver.current?.();milestoneResolver.current=null};
 const confirmPerfectReward=()=>{setPerfectRewardNotice(null);perfectRewardResolver.current?.();perfectRewardResolver.current=null};
 const handleStartPass=async(s:GameState,p:PlayerState)=>{
  if(!config||!activeCharacter||!activeId)return;
  const reward=config.cells.find(cell=>cell.id===0)?.startRewards?.[p.characterId]??0;
  p.stats.money=Math.max(0,p.stats.money+reward);log(s,`${activeCharacter.name}通過起點，獲得金錢 +${reward}`);setState(structuredClone(s));playOutcome("cheer");
  await new Promise<void>(resolve=>{startNoticeResolver.current=resolve;setStartPassNotice({characterId:activeId,reward,money:p.stats.money})});
  if(p.stage>=5)return;const threshold=activeCharacter.thresholds[p.stage];
  if(!meets(p,threshold.min)){log(s,`尚未達到「${stageLabels[p.stage]}」門檻，繼續累積能力`);return}
  const perfect=meets(p,threshold.perfect);p.stage++;
  if(p.stage===5){p.finishedAt=Date.now();log(s,`🏆 ${activeCharacter.name}成為${activeCharacter.job}大師！`)}else log(s,`${activeCharacter.name}進階成為${activeCharacter.titles[p.stage]}`);
  setState(structuredClone(s));await new Promise<void>(resolve=>{milestoneResolver.current=resolve;setMilestoneNotice({characterId:activeId,stage:p.stage,perfect})});
  if(perfect){const effects=threshold.perfectReward??{money:300,mood:1};applyEffects(p,effects);log(s,`${threshold.perfectDescription||"完美通關！"} ${effectText(effects)}`);setState(structuredClone(s));await new Promise<void>(resolve=>{perfectRewardResolver.current=resolve;setPerfectRewardNotice({characterId:activeId,effects,description:threshold.perfectDescription||"完美通關！"})})}
 }; const moveByDice=async(raw:number)=>{
  if(!state||!config||!active||!activeCharacter||pending||rolling)return;
  const s=structuredClone(state) as GameState;const p=s.players[activeId!];
  if(p.skipTurns>0){p.skipTurns--;log(s,`${activeCharacter.name}暫停一回合`);nextTurn(s);await save(s,"skip");return}
  setRolling(true);setDice(raw);const steps=raw*(s.accelerated?2:1);setRollMessage(`實體骰子擲出 ${raw}！${s.accelerated?`加速前進 ${steps} 格`:`前進 ${steps} 格`}`);await wait(250);
  for(let step=0;step<steps;step++){const trackIndex=perimeter.indexOf(p.position);p.position=perimeter[(trackIndex+1)%perimeter.length];playClip("/assets/audio/walking.mp3",280,.65);setState(structuredClone(s));await wait(300);if(p.position===0)await handleStartPass(s,p)}
  log(s,`${activeCharacter.name}實體骰子擲出 ${raw}${s.accelerated?`，加速前進 ${steps} 格`:""}`);
  const beforeEventStats={...p.stats};
  const cell=config.cells[p.position];setRolling(false);
  if(p.stage===5){notifyStats(activeId!,beforeEventStats,p.stats);setPending({kind:"info",title:"完成使命！",description:`${activeCharacter.name}已靠著信仰重新站立，成為頂天立地的${activeCharacter.job}大師！`});await save(s,"finish");return}
  if(cell.type==="chance"||cell.type==="destiny"){notifyStats(activeId!,beforeEventStats,p.stats);drawCard(s,p,cell.type);await save(s,"draw");return}
  if(cell.choice==="overtime"){notifyStats(activeId!,beforeEventStats,p.stats);setPending({kind:"overtime"});await save(s,"land");return}
  if(cell.choice==="class"){notifyStats(activeId!,beforeEventStats,p.stats);setPending({kind:"class"});await save(s,"land");return}
  const shouldAdvance=settle(s,cell,p);const cellChanges=statChanges(beforeEventStats,p.stats);if(Object.values(cellChanges).some(value=>(value||0)<0))playOutcome("sad");else if(Object.values(cellChanges).some(value=>(value||0)>0))playOutcome("cheer");notifyStats(activeId!,beforeEventStats,p.stats,cell.label);if(shouldAdvance)nextTurn(s);await save(s,"roll");
 };
 const chooseCard=(card:Card)=>{if(!state||!config||!activeId)return;const s=structuredClone(state) as GameState;const p=s.players[activeId];const key=`${card.type}-${card.contentStage}`;const pool=config.cards.filter(item=>item.characterId===card.characterId&&item.contentStage===card.contentStage&&item.type===card.type);const used=p.decks[key]||[];const base=pool.every(item=>used.includes(item.id))?[]:used;p.decks[key]=[...base,card.id];setPending({kind:"card",card});log(s,`選中了${card.type==="chance"?"機會":"命運"}卡「${card.title}」`);save(s,"choose-card")}; const resolve=(effects?:Effects,note="事件結算",peaceCards=0,contextLabel?:string,resultDescription?:string)=>{if(!state||!activeId)return;const s=structuredClone(state) as GameState;const p=s.players[activeId];const before={...p.stats};if(effects){const negative=Object.values(effects).some(v=>(v||0)<0);if(negative&&p.peaceCards>0){p.peaceCards--;log(s,"平安卡自動發動，抵銷本次負面影響！")}else applyEffects(p,effects)}if(peaceCards>0){p.peaceCards+=peaceCards;log(s,`獲得平安卡 × ${peaceCards}`)}log(s,note);notifyStats(activeId,before,p.stats,contextLabel);if(resultDescription)setResultNotice({title:"選擇結果",description:resultDescription});setPending(null);nextTurn(s);save(s,"resolve")}; const buyClass=(key:"stamina"|"intelligence"|"eq")=>{if(!active)return;if(active.stats.money<100){setMessage("金錢不足 100，無法購買課程。");return}playOutcome("cheer");resolve({money:-100,[key]:1},`上課進修：花 100 元提升${labels[key]}`,0,"上課")};
 const start=()=>{if(!state)return;const s=structuredClone(state);s.started=true;log(s,"守護天使畢業考正式開始！");save(s,"start")};
 const moveOrder=(id:string,dir:number)=>{if(!state)return;const s=structuredClone(state);const i=s.turnOrder.indexOf(id);const j=i+dir;if(j<0||j>=s.turnOrder.length)return;[s.turnOrder[i],s.turnOrder[j]]=[s.turnOrder[j],s.turnOrder[i]];setState(s)};
 const toggleSpeed=()=>{if(!state||rolling)return;const s=structuredClone(state);s.accelerated=!s.accelerated;log(s,`加速模式已${s.accelerated?"開啟":"關閉"}`);save(s,"speed")};
 if(loading||!config||!state)return <main className="loading"><div className="spinner">🎲</div><p>正在載入生涯旅程…</p></main>;
 const finished=Object.values(state.players).filter(p=>p.finishedAt!==null).length;
 return <main>
  <header className="game-intro">
   <div className="site-tools"><span className={message?"status offline":"status"}>{message||(saving?"儲存中…":"雲端已同步")}</span><span className="version-badge">{SITE_VERSION}</span><a href="/admin" className="ghost">管理設定 ⚙️</a></div><div className="intro-copy"><p className="eyebrow">PENIEL YOUTH CAREER CAMP</p><span className="pill">守護天使畢業考</span><h1>{config.title}</h1><p>{config.story}</p></div>
   <div className="hero-badge"><b>{finished}/4</b><span>已成為大師</span></div>
  </header>
  {!state.started&&<section className="setup card"><div><p className="eyebrow">STEP 01</p><h2>決定出發順序</h2><p>四組守護天使討論好後，用箭頭調整順序。</p></div><div className="order-list">{state.turnOrder.map((id,i)=>{const c=config.characters.find(x=>x.id===id)!;return <div className="order-item" key={id}><b>{i+1}</b><Portrait id={c.id} name={c.name}/><span><strong>{c.name}</strong><small>{c.job}</small></span><button onClick={()=>moveOrder(id,-1)} disabled={i===0}>↑</button><button onClick={()=>moveOrder(id,1)} disabled={i===3}>↓</button></div>})}</div><button className="primary big" onClick={start}>開始冒險 →</button></section>}
  {state.started&&<>
   <section className="characters-section"><div className="section-heading"><div><p className="eyebrow">GUARDIAN TEAMS</p><h2>守護對象</h2></div><span>第 {state.round} 輪</span></div><div className="characters-row">{config.characters.map(c=>{const p=state.players[c.id];const isActive=c.id===activeId;const nextThreshold=p.stage<5?c.thresholds[p.stage]?.min:null;return <article className={`player-card ${isActive?"active":""} ${p.finishedAt?"finished":""}`} key={c.id} style={{"--accent":c.color} as React.CSSProperties}><div className="player-head"><Portrait id={c.id} name={c.name}/><div><small>{c.instrument}</small><h3>{c.name}</h3><b>目標・{c.job}</b></div>{isActive&&<span className="turn-tag">行動中</span>}</div><div className="stage career-stage" tabIndex={0}><span>職稱</span><strong>{c.titles[p.stage]||"尚未設定"}</strong><div className="career-tooltip" role="tooltip">{nextThreshold?<><b>下個目標・{stageLabels[p.stage]}</b><span>最低能力門檻</span><div>{Object.entries(nextThreshold).filter(([,value])=>(value||0)>0).map(([key,value])=><em key={key}>{labels[key as StatKey]} {value}</em>)}</div><small>達標並通過起點即可進階</small></>:<><b>生涯旅程已完成</b><span>已成為頂天立地的大師！</span></>}</div></div><div className="stats">{(["stamina","intelligence","eq","mood"] as StatKey[]).map(k=><div key={k}><span>{labels[k]}</span><b>{p.stats[k]}</b></div>)}</div><div className="money">💰 {p.stats.money}<span>🕊️ × {p.peaceCards}</span></div></article>})}</div></section>
   <details className="journey-details card"><summary><span>📖 旅程紀錄</span><small>點擊展開・最新紀錄在上</small></summary><div className="log-list">{state.log.map((x,i)=><p key={i}><span>{i===0?"●":"○"}</span>{x}</p>)}</div></details>
   <section className="board-stage"><div className="board">{perimeter.map((cellId,index)=>{const cell=config.cells[cellId];const pieces=config.characters.filter(c=>state.players[c.id].position===cellId);return <div key={cellId} className={`board-cell cell-${index} ${cell.type}`}><span className="cell-icon">{cell.icon}</span><b>{cell.label}</b><div className="pieces">{pieces.map(c=><span key={c.id} className={c.id===activeId&&rolling?"piece-moving":""} style={{borderColor:c.color}} title={c.name}><Portrait id={c.id} name={c.name} size="mini"/></span>)}</div></div>})}<div className="board-center"><p className="eyebrow">NOW PLAYING</p><Portrait id={activeCharacter?.id||"goto"} name={activeCharacter?.name||""} size="large"/><h2>{activeCharacter?.name}</h2><p>前進吧，守護天使！</p>{rollMessage&&<div className="roll-result"><b>{dice?diceFaces[dice-1]:"🎲"}</b><span>{rollMessage}</span></div>}<div className="physical-dice-picker"><b>輸入實體骰子結果</b><small>{rolling?"角色移動中…":"學生擲完骰子後，請主持人點選點數"}</small><div>{diceFaces.map((face,index)=><button key={face} className={dice===index+1?"selected":""} onClick={()=>moveByDice(index+1)} disabled={saving||rolling||!!pending} aria-label={`骰子點數 ${index+1}`}><span>{face}</span><em>{index+1}</em></button>)}</div></div><button className={`speed ${state.accelerated?"on":""}`} onClick={toggleSpeed} disabled={rolling}>⚡ 加速模式 {state.accelerated?"ON":"OFF"}</button>{startPassNotice&&!milestoneNotice&&(()=>{const c=config.characters.find(item=>item.id===startPassNotice.characterId);return c?<div className="board-start-overlay"><section className="start-pass-dialog card" style={{"--accent":c.color} as React.CSSProperties}><div className="start-pass-icon">🎓</div><p className="eyebrow">PASSING START</p><h2>通過起點！</h2><h3>{c.name} 獲得 <strong>＋{startPassNotice.reward}</strong> 元</h3><p>目前金錢：{startPassNotice.money}</p><button className="primary big" onClick={confirmStartPass}>確認並繼續</button></section></div>:null})()}{statNotice&&!milestoneNotice&&!perfectRewardNotice&&!resultNotice&&!startPassNotice&&(()=>{const c=config.characters.find(item=>item.id===statNotice.characterId);return c?<div className="board-stat-overlay"><section className="board-stat-dialog card" style={{"--accent":c.color} as React.CSSProperties}><div className="stat-notice-head"><Portrait id={c.id} name={c.name}/><div><small>{statNotice.contextLabel?`${statNotice.contextLabel}後能力現況`:"事件結算後能力現況"}</small><h3>{c.name}・{c.job}</h3></div></div><div className="stat-notice-grid">{(["stamina","intelligence","eq","mood","money"] as StatKey[]).map(key=>{const delta=statNotice.changes[key]||0;return <div className={delta?"changed":""} key={key}><span>{labels[key]}</span><b>{statNotice.stats[key]}</b>{delta>0&&<em className="stat-delta up">↑ +{delta}</em>}{delta<0&&<em className="stat-delta down">↓ {Math.abs(delta)}</em>}</div>})}</div><button className="primary stat-confirm" onClick={()=>setStatNotice(null)}>確認</button></section></div>:null})()}</div></div></section>
  </>}
    {milestoneNotice&&(()=>{const c=config.characters.find(item=>item.id===milestoneNotice.characterId);const threshold=c?.thresholds[milestoneNotice.stage-1];return c?<div className="milestone-backdrop"><section className="milestone-dialog card" style={{"--accent":c.color} as React.CSSProperties}><div className="milestone-sparkles">✦　⭐　✦</div><Portrait id={c.id} name={c.name} size="large"/><p className="eyebrow">MAJOR MILESTONE</p><h2>{milestoneNotice.stage===5?"成為頂天立地的大師！":"重大事件突破！"}</h2><h3>{c.name}進階從「{c.titles[milestoneNotice.stage-1]}」成為「{c.titles[milestoneNotice.stage]}」</h3><p>{threshold?.milestoneDescription||"守護天使的陪伴，讓生涯旅程邁入下階段。"}</p><button className="primary big" onClick={confirmMilestone}>繼續旅程</button></section></div>:null})()}
    {perfectRewardNotice&&(()=>{const c=config.characters.find(item=>item.id===perfectRewardNotice.characterId);return c?<div className="perfect-reward-backdrop"><section className="perfect-reward-dialog card" style={{"--accent":c.color} as React.CSSProperties}><div className="perfect-crown">👑</div><p className="eyebrow">PERFECT CLEAR</p><h2>完美通關獎勵！</h2><h3>{perfectRewardNotice.description}</h3><div className="perfect-reward-effects">{effectText(perfectRewardNotice.effects)}</div><button className="primary big" onClick={confirmPerfectReward}>領取獎勵並繼續</button></section></div>:null})()}
    {resultNotice&&!milestoneNotice&&!perfectRewardNotice&&<div className="result-notice-backdrop"><section className="result-notice-dialog card"><div className="result-notice-icon">✨</div><p className="eyebrow">RESULT</p><h2>{resultNotice.title}</h2><p>{resultNotice.description}</p><button className="primary big" onClick={()=>setResultNotice(null)}>確認</button></section></div>}
    {pending&&<div className="modal-backdrop"><section className={`modal card ${pending.kind==="cardChoice"?"card-choice-modal":""}`}>{pending.kind==="cardChoice"&&<><span className={`card-type ${pending.type}`}>{pending.type==="chance"?"✨ 機會卡":"🌙 命運卡"}</span><h2>{pending.type==="chance"?"機會來臨！":"命運在你手中"}</h2><p>請守護天使選擇一張牌，看看旅程將發生什麼事！</p><div className="card-choice-grid">{pending.cards.map((card,index)=><button key={card.id} className={`mystery-card ${pending.type}`} aria-label={`選擇第 ${index+1} 張${pending.type==="chance"?"機會":"命運"}卡`} onClick={()=>chooseCard(card)}><span className="card-back-symbol">{pending.type==="chance"?"✦":"☾"}</span><b>{pending.type==="chance"?"機會":"命運"}</b><small>選擇這張</small></button>)}</div><p className="choice-footnote">本階段抽過的卡片，在全部抽完前不會重複。</p></>}{pending.kind==="card"&&(()=>{const card=pending.card;const mode=card.resolutionMode??(card.task?"task":"automatic");return <><span className={`card-type ${card.type}`}>{card.type==="chance"?"✨ 機會卡":"🌙 命運卡"}</span><h2>{card.title}</h2><p>{card.description}</p>{card.instruction&&<div className="instruction-box"><b>🎬 現場動態任務</b><span>{card.instruction}</span></div>}{mode==="choice"?<><div className="choice-hint">請守護天使討論後選擇一項</div><div className="modal-actions choice-actions"><button onClick={()=>resolve(card.optionA?.effects,`選擇「${card.optionA?.label}」：${card.title}`,card.optionA?.peaceCards||0,undefined,card.optionA?.resultDescription||"真好！")} className="ghost"><b>{card.optionA?.label||"選項一"}</b><small>{effectText(card.optionA?.effects)}</small></button><button onClick={()=>resolve(card.optionB?.effects,`選擇「${card.optionB?.label}」：${card.title}`,card.optionB?.peaceCards||0,undefined,card.optionB?.resultDescription||"真好！")} className="primary"><b>{card.optionB?.label||"選項二"}</b><small>{effectText(card.optionB?.effects)}</small></button></div></>:mode==="task"?<><div className="effect-comparison"><span>失敗：{effectText(card.failureEffects)}</span><span>成功：{effectText(card.successEffects)}</span></div><div className="modal-actions"><button onClick={()=>resolve(card.failureEffects,`${card.failureLabel||"任務失敗"}：${card.title}`,card.failurePeaceCards||0)} className="ghost">{card.failureLabel||"任務失敗"}</button><button onClick={()=>resolve({...card.effects,...card.successEffects},`${card.successLabel||"任務成功"}：${card.title}`,card.successPeaceCards||0)} className="primary">{card.successLabel||"任務成功"}</button></div></>:<><div className="effect-box">{effectText(card.effects)}</div><button className="primary wide" onClick={()=>resolve(card.effects,`完成卡片：${card.title}`,card.peaceCards||0)}>套用結果</button></>}</>})()}
  {pending.kind==="overtime"&&<><span className="card-type destiny">🌃 人生選擇</span><h2>今晚要加班嗎？</h2><p>努力可以帶來收入，也要留意身心的代價。</p><div className="effect-box">體力 -1・心情 -1・金錢 +200</div><div className="modal-actions"><button className="ghost" onClick={()=>resolve(undefined,"婉拒加班，選擇休息")}>婉拒加班</button><button className="primary" onClick={()=>resolve({stamina:-1,mood:-1,money:200},"接受加班",0,"加班格")}>接受加班</button></div></>}
  {pending.kind==="class"&&<><span className="card-type chance">🧑‍🏫 投資自己</span><h2>選一堂課程</h2><p>支付 100 元，提升一項能力。</p><div className="modal-actions three"><button onClick={()=>buyClass("stamina")}>體力 +1</button><button onClick={()=>buyClass("intelligence")}>智力 +1</button><button onClick={()=>buyClass("eq")}>情商 +1</button></div><button className="text-button" onClick={()=>resolve(undefined,"這次先不上課")}>這次先不上課</button></>}
  {pending.kind==="info"&&<><span className="card-type chance">🕊️ 特別事件</span><h2>{pending.title}</h2><p>{pending.description}</p><button className="primary wide" onClick={()=>resolve(undefined,pending.title)}>繼續旅程</button></>}</section></div>}
 </main>
}
